"""
Django settings for primerdesign project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import json
from pathlib import Path
from .logging.conf import LOGGING


# Project paths
BASE_DIR = Path(__file__).resolve().parent.parent

PRIMER3_PATH = os.path.join(
    BASE_DIR,
    'design',
    'primer3',
    'src',
    'primer3_core'
)
PRIMER3_CONFIG_PATH = os.path.join(
    BASE_DIR,
    'design',
    'primer3',
    'src',
    'primer3_config'
)
PRIMER3_INPUT_DIR = os.path.join(
    BASE_DIR,
    'design',
    'primer3',
    'input_files'
)
PROBE_SEQUENCE_PATH = os.path.join(
    BASE_DIR,
    'design',
    'probes',
    'roche_upl_sequences.json'
)
PATHS = [
    ('PRIMER3_PATH', PRIMER3_PATH),
    ('PRIMER3_INPUT_DIR', PRIMER3_INPUT_DIR),
    ('PROBE_SEQUENCE_PATH', PROBE_SEQUENCE_PATH),
]

if not os.path.exists(PRIMER3_INPUT_DIR):
    try:
        os.mkdir(PRIMER3_INPUT_DIR)
    except:
        raise FileNotFoundError(
            'Failed to create directory for input files at '
            + PRIMER3_INPUT_DIR
        )

for name, path in PATHS:
    assert os.path.exists(path), (
        f"Path not found at settings.{name}:"
        + f" { path }"
    )

### Parameters ###

# Minimum nt distance between probe and primers
MIN_PROBE_DISTANCE = 10

# UPL probe sequences
with open(PROBE_SEQUENCE_PATH) as f:
    UPL_PROBES = json.load(f)

# General config
DEBUG = True
SECRET_KEY = '&6zt9-fu%_%6l4y34lhjh4u*z+mda@wx6dzr3bx0ay3sqfy!w^'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'design',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'primerdesign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'primerdesign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Australia/Brisbane'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'primerdesign', 'static')
